name: Cross-Platform CI

on:
  push:
    branches: [trunk, main, 'v*.x', 'ci/*']
  pull_request:
    branches: [trunk, main, 'v*.x']

env:
  CARGO_TERM_COLOR: always

jobs:
  test-zig:
    name: Test (${{ matrix.platform }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: aarch64-unknown-linux-gnu
            zig_target: aarch64-unknown-linux-gnu.2.28
            qemu_arch: aarch64
          - platform: aarch64-unknown-linux-musl
            zig_target: aarch64-unknown-linux-musl
            qemu_arch: aarch64
          - platform: riscv64gc-unknown-linux-gnu
            zig_target: riscv64gc-unknown-linux-gnu.2.28
            qemu_arch: riscv64
          - platform: x86_64-unknown-linux-musl
            zig_target: x86_64-unknown-linux-musl
            qemu_arch: ""

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.91.1
          targets: ${{ matrix.platform }}

      - name: Install Dependencies
        run: |
          sudo pip3 install ziglang
          cargo install cargo-zigbuild --locked
          sudo apt-get update && sudo apt-get install -y qemu-user-static

      - uses: Swatinem/rust-cache@v2

      - name: Run Tests
        shell: bash
        run: |
          export CC="zig cc -target ${{ matrix.zig_target }}"
          export CXX="zig c++ -target ${{ matrix.zig_target }}"
          
          if [ -n "${{ matrix.qemu_arch }}" ]; then
            ENV_NAME=$(echo ${{ matrix.platform }} | tr '[:lower:]-' '[:upper:]_')
            export CARGO_TARGET_${ENV_NAME}_RUNNER="qemu-${{ matrix.qemu_arch }}-static"
          fi
          
          cargo zigbuild --target ${{ matrix.zig_target }} --all-features
          cargo test --target ${{ matrix.zig_target }} --all-features