name: Publish to crates.io

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: publishing
      url: https://crates.io/crates/bincode-next

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install Rust
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # master
      - name: Publish to crates.io
        run: |
          cd derive
          cargo package
          ID_TOKEN=$(curl -sSL "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=crates.io" -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value')
          CRATE_FILE=$(find ../target/package -name "*.crate")
          curl -H "Authorization: $ID_TOKEN" \
            -H "Content-Type: application/json" \
            -X PUT \
            --data-binary @$CRATE_FILE \
            https://crates.io/api/v1/crates/new
          cd ..
          cargo package
          ID_TOKEN=$(curl -sSL "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=crates.io" -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value')
          CRATE_FILE=$(find ./target/package -name "*.crate")
          curl -H "Authorization: $ID_TOKEN" \
            -H "Content-Type: application/json" \
            -X PUT \
            --data-binary @$CRATE_FILE \
            https://crates.io/api/v1/crates/new
