name: Publish to crates.io

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: publishing
      url: https://crates.io/crates/bincode-next
    
    permissions:
      id-token: write
      contents: read
    
    steps:
      # Pin actions/checkout v4.2.2
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      
      # Pin dtolnay/rust-toolchain (latest stable)
      - uses: dtolnay/rust-toolchain@8f51a215752c0199994f1c990a911762c5e5330a # master
      
      # Pin katyo/publish-crates v2.3.0
      - uses: katyo/publish-crates@5e676395995873941433020619623e114092b740 # v2.3.0
        with:
          registry-token: ${{ secrets.CRATES_IO_TOKEN }}